extends: airbnb/base
# plugins:
  # - mocha
globals:
  describe: true
  it: true
  beforeEach: true
  afterEach: true
  Promise: true
rules:
  indent:
    - error
    - 4
  max-len:
    - error
    - 120
    - ignoreComments: true
    - ignoreUrls: true
  global-require: 0
  vars-on-top: 0
  padded-blocks: 0
  no-console: 0
  prefer-const: 0
  prefer-template: 0
  comma-dangle: 0
  consistent-return: 0
  no-param-reassign: 0
  no-underscore-dangle: 0
  no-unused-vars:
    - warn
    - varsIgnorePattern: "process"
  import/no-unresolved:
    - "error"
    - ignore:
        - state
